### ISSUE TITLE
Convert images to data URIs

### ISSUE THREAD

**Issue by nikclayton** [dangom/writefreely.el#16]
Since write.as doesn't support hosting images directly, it would be handy if images linked to from the Org file were converted to data: URIs when the content is uploaded.

**Comment by dangom** [comment]
Converting them to data URIs is [easy](https://emacs.stackexchange.com/questions/27060/embed-image-as-base64-on-html-export-from-orgmode/27065#27065), the problem is that write.as ignores <img> tags.
```elisp
#+BEGIN_SRC emacs-lisp :results verbatim :exports both
(defun tob64 (filename)
  (base64-encode-string
   (with-temp-buffer
     (insert-file-contents filename)
     (buffer-string))))

(format "<img src=\"data:image/png;base64,%s\">"
    (tob64 "/path/to/img"))
#+END_SRC
```

**Comment by nikclayton** [comment]
I opened an issue over there about that -- https://github.com/writeas/writefreely/issues/80.

**Comment by dangom** [comment]
I've finally added rudimentary support for this by uploading images to snap.as. It's unfortunately a "proprietary" solution for now, but seems to work ok.
