### ISSUE TITLE
Don't extract the encrypted token when the mode is loaded ?

### ISSUE THREAD

**Issue by JekoTronik** [dangom/writefreely.el#24]
From my conf file :
```emacs-lisp
(setq epa-pinentry-mode 'loopback)
(use-package writefreely
  :ensure t
  :after org
  :requires ox-gfm
  :requires request
  :config
  (load-library (expand-file-name "writefreely-auth-token.el.gpg" user-emacs-directory))
  (add-hook 'org-mode-hook 'writefreely-mode))
```
From writefreely-auth-token.el.gpg
```emacs-lisp
;;; -*- epa-file-encrypt-to: ("my-email-address") -*-

(setq writefreely-auth-token "my-token")
```
I need to evaluate manually the line `(load-library (expand-file-name "writefreely-auth-token.el.gpg" user-emacs-directory))` to make it to work. Otherwise, writefreely.el will publish posts as an anonymous user.
With the token pasted into the conf file it works : `(setq writefreely-auth-token "my-token")`

**Comment by dangom** [comment]
Not sure. Maybe try putting it in the init form instead of config and demand the package? Also, no need to add that hook.

**Comment by JekoTronik** [comment]
Here is what finally worked for me !
```emacs-lisp
(setq epa-pinentry-mode 'loopback)
(use-package writefreely
  :ensure t
  :hook ('org-mode-hook 'writefreely-mode)
  :after org
  :init (load (expand-file-name "writefreely-auth-token.el.gpg" user-emacs-directory)))
```
Thank you for your recommendations, Dani !

**Comment by dangom** [comment]
You don't. I think the issue is that writefreely has no reason to load otherwise. Are you setting `(setq-default use-package-always-defer t)`? Also, when setting hooks with use-package the syntax should be `:hook (org-mode . writefreely-mode)` per [the docs.](https://github.com/jwiegley/use-package#hooks)

**Comment by JekoTronik** [comment]
You're right ! I don't use `use-package-always-defer`. With a bit of reading here is what I end up with : 
```emacs-lisp
(setq epa-pinentry-mode 'loopback) ;; I want the passphrase to be ask inside emacs minibuffer
(use-package writefreely
  :ensure t
  :hook org-mode
  :config (load (expand-file-name "writefreely-auth-token.el.gpg" user-emacs-directory)))
```
Thank you for your help @dangom and for this cool extension !
